<# =======================================================================
 Install-ServerStack.ps1
 - Downloads & lays out: Caddy, nginx (Windows), NSSM
 - Installs the app's Python requirements into the venv - offline from
   WheelsDir when it exists - including gevent, the production server
 - Idempotent: safe to re-run; only (re)downloads when missing
 - Tested with PowerShell 7+ on Windows Server 2019
 ======================================================================= #>

# ---------------- CONFIG (adjust if needed) ----------------
$Config = [ordered]@{
  # Where your app + venv live
  AppRoot        = 'G:\srv\app\itracker'
  VenvPython     = 'G:\srv\app\itracker\venv\Scripts\python.exe'  # pip installs Requirements.txt here
  AppPort        = 5001
  # Offline wheels (exec_prod\wheels from the repo, copied to the server). If the
  # folder is missing, requirements are installed from PyPI instead.
  WheelsDir      = 'G:\srv\app\itracker\exec_prod\wheels'

  # Caddy
  CaddyDir       = 'C:\Tools\Caddy'
  CaddyExe       = 'C:\Tools\Caddy\caddy.exe'
  Caddyfile      = 'C:\Tools\Caddy\Caddyfile'
  # Caddy download API returns the proper EXE for Windows/amd64
  CaddyDownload  = 'https://caddyserver.com/api/download?os=windows&arch=amd64'

  # nginx (Windows). Set the version you want:
  NginxVersion   = '1.25.5'                                     # <-- change if you want a different version
  NginxZipUrl    = ''                                           # if blank, script builds from version
  NginxDir       = 'C:\nginx'                                   # final folder (nginx.exe ends up here)

  # NSSM
  NssmDir        = 'C:\Tools\NSSM'
  NssmExe        = 'C:\Tools\NSSM\nssm.exe'
  NssmZipUrl     = 'https://nssm.cc/release/nssm-2.24.zip'

  # PATH
  AddToPath      = $true

  # Trust Caddy local root CA (for local HTTPS without warnings)
  CaddyTrustCA   = $true
}

# ---------------- Utility helpers ----------------
function Assert-Admin {
  $id = [Security.Principal.WindowsIdentity]::GetCurrent()
  $pr = New-Object Security.Principal.WindowsPrincipal $id
  if (-not $pr.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Please run this script in an elevated PowerShell 7 session (Run as administrator)."
  }
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Path $Path -Force | Out-Null }
}

function Download-IfMissing {
  param(
    [Parameter(Mandatory)] [string]$Url,
    [Parameter(Mandatory)] [string]$Destination
  )
  if (Test-Path $Destination) {
    Write-Host "Already present: $Destination"
    return $Destination
  }
  Write-Host "Downloading $Url ..."
  Invoke-WebRequest -Uri $Url -OutFile $Destination -UseBasicParsing
  return $Destination
}

function Add-ToSystemPath([string]$Dir) {
  if (-not $Config.AddToPath) { return }
  $current = [Environment]::GetEnvironmentVariable('Path', 'Machine')
  if ($current -notlike "*$Dir*") {
    [Environment]::SetEnvironmentVariable('Path', ($current.TrimEnd(';') + ';' + $Dir), 'Machine')
    Write-Host "Added to PATH (system): $Dir"
  } else {
    Write-Host "PATH already contains: $Dir"
  }
}

# ---------------- Main steps ----------------
try {
  Assert-Admin

  # 1) CADDY ------------------------------------------------
  Ensure-Dir $Config.CaddyDir
  if (-not (Test-Path $Config.CaddyExe)) {
    $tmp = Join-Path $env:TEMP "caddy.exe"
    Download-IfMissing -Url $Config.CaddyDownload -Destination $tmp | Out-Null
    Copy-Item $tmp $Config.CaddyExe -Force
    Remove-Item $tmp -Force -ErrorAction SilentlyContinue
    Write-Host "Placed caddy at $($Config.CaddyExe)"
  } else {
    Write-Host "Caddy already present at $($Config.CaddyExe)"
  }
  Add-ToSystemPath $Config.CaddyDir

  # Write a minimal Caddyfile (idempotent: only if absent)
  if (-not (Test-Path $Config.Caddyfile)) {
    $caddyLines = @(
      '# Caddyfile generated by Install-ServerStack.ps1'
      '# Caddy passes the Socket.IO WebSocket upgrade through and sends'
      '# X-Forwarded-For/-Proto itself: set TRUST_PROXY_HOPS=1 in the app''s .env.'
      'localhost {'
      '    tls internal'
      '    encode gzip'
      "    reverse_proxy 127.0.0.1:$($Config.AppPort)"
      '}'
    )
    $caddyLines | Set-Content -Path $Config.Caddyfile -Encoding ascii
    Write-Host "Wrote Caddyfile at $($Config.Caddyfile)"
  } else {
    Write-Host "Caddyfile already exists at $($Config.Caddyfile)"
  }

  # Optionally trust Caddy local root CA for clean local HTTPS
  if ($Config.CaddyTrustCA -and (Test-Path $Config.CaddyExe)) {
    Write-Host "Installing Caddy local root CA into Windows trust (if not already trusted)..."
    & $Config.CaddyExe trust | Out-Host
  }

  # 2) NSSM -------------------------------------------------
  Ensure-Dir $Config.NssmDir
  if (-not (Test-Path $Config.NssmExe)) {
    $nssmZip = Join-Path $env:TEMP "nssm.zip"
    Download-IfMissing -Url $Config.NssmZipUrl -Destination $nssmZip | Out-Null
    $nssmTmp = Join-Path $env:TEMP "nssm_extracted"
    if (Test-Path $nssmTmp) { Remove-Item $nssmTmp -Recurse -Force }
    Expand-Archive -Path $nssmZip -DestinationPath $nssmTmp -Force
    # Copy win64 build
    $candidate = Get-ChildItem -Path (Join-Path $nssmTmp 'nssm-*\win64\nssm.exe') -ErrorAction Stop | Select-Object -First 1
    Copy-Item $candidate.FullName $Config.NssmExe -Force
    Remove-Item $nssmTmp -Recurse -Force
    Write-Host "Placed NSSM at $($Config.NssmExe)"
  } else {
    Write-Host "NSSM already present at $($Config.NssmExe)"
  }
  Add-ToSystemPath $Config.NssmDir

  # 3) NGINX (Windows) -------------------------------------
  # Build default ZIP URL if not overridden
  $nginxZipUrl = if ([string]::IsNullOrWhiteSpace($Config.NginxZipUrl)) {
    "https://nginx.org/download/nginx-$($Config.NginxVersion).zip"
  } else { $Config.NginxZipUrl }

  if (-not (Test-Path (Join-Path $Config.NginxDir 'nginx.exe'))) {
    $nginxZip = Join-Path $env:TEMP "nginx.zip"
    Download-IfMissing -Url $nginxZipUrl -Destination $nginxZip | Out-Null
    # Extract into TEMP and then move into C:\nginx to avoid nested folder names
    $tmpExtract = Join-Path $env:TEMP "nginx_extracted"
    if (Test-Path $tmpExtract) { Remove-Item $tmpExtract -Recurse -Force }
    Expand-Archive -Path $nginxZip -DestinationPath $tmpExtract -Force
    # Typical structure: <temp>\nginx-<ver>\*
    $root = Get-ChildItem -Path $tmpExtract -Directory | Select-Object -First 1
    Ensure-Dir $Config.NginxDir
    Copy-Item -Path (Join-Path $root.FullName '*') -Destination $Config.NginxDir -Recurse -Force
    Remove-Item $tmpExtract -Recurse -Force
    Write-Host "Placed nginx at $($Config.NginxDir)"
  } else {
    Write-Host "nginx already present at $($Config.NginxDir)"
  }

  # 4) APP REQUIREMENTS (pip in your venv) ------------------
  # Includes gevent + gevent-websocket: `python app.py` in gevent mode is the
  # production server. Waitress is not used - it cannot carry WebSockets.
  $req = Join-Path $Config.AppRoot 'Requirements.txt'
  if ((Test-Path $Config.VenvPython) -and (Test-Path $req)) {
    if ($Config.WheelsDir -and (Test-Path $Config.WheelsDir)) {
      Write-Host "Installing app requirements offline from $($Config.WheelsDir)"
      & $Config.VenvPython -m pip install --no-index --find-links $Config.WheelsDir -r $req | Out-Host
    } else {
      Write-Host "Installing app requirements from PyPI"
      & $Config.VenvPython -m pip install -r $req | Out-Host
    }
    if ($LASTEXITCODE -ne 0) { throw "pip could not install $req - see the output above." }
    & $Config.VenvPython -c "import gevent, geventwebsocket; print('gevent', gevent.__version__, 'ready')" | Out-Host
  } else {
    Write-Warning "Venv Python or Requirements.txt not found under $($Config.AppRoot). Skipping app requirements."
  }

  Write-Host "`nAll done."
  Write-Host "Caddy:  $($Config.CaddyExe)"
  Write-Host "NSSM:   $($Config.NssmExe)"
  Write-Host "nginx:  $(Join-Path $Config.NginxDir 'nginx.exe')"
  Write-Host "Caddyfile: $($Config.Caddyfile)"
  Write-Host "`nTip: open a new console to pick up PATH changes."
}
catch {
  Write-Error $_.Exception.Message
  throw
}